import { vi } from 'vitest';
import type { PantryItem, ShoppingListItem } from '@/types';

/** Minimal stabiler Stub fuer PantryManager-Shell-Smoke (alle Context-Konsumenten). */
export function createPantryManagerSmokeStub() {
  return {
    searchTerm: '',
    setSearchTerm: vi.fn(),
    sortOrder: 'name' as const,
    setSortOrder: vi.fn(),
    isGrouped: false,
    setIsGrouped: vi.fn(),
    expiryFilter: 'all' as const,
    setExpiryFilter: vi.fn(),
    modalState: { isOpen: false, item: null as PantryItem | null },
    setModalState: vi.fn(),
    isSelectMode: false,
    selectedItems: [] as number[],
    pantryItems: [] as PantryItem[],
    filteredItems: [] as PantryItem[],
    groupedItems: null as Record<string, PantryItem[]> | null,
    searchInputRef: { current: null as HTMLInputElement | null },
    pendingAction: null,
    confirmationDialog: null,
    confirmPendingAction: vi.fn(),
    cancelPendingAction: vi.fn(),
    adjustQuantity: vi.fn(),
    toggleSelectItem: vi.fn(),
    toggleSelectMode: vi.fn(),
    handleDeleteSelected: vi.fn(),
    handleAddSelectedToShoppingList: vi.fn(),
    handleSaveItem: vi.fn(),
    handleAddToShoppingList: vi.fn(),
    handleQuickAdd: vi.fn(),
  };
}

/** Minimal stabiler Stub fuer ShoppingList-Shell-Smoke (alle Context-Konsumenten). */
export function createShoppingListSmokeStub() {
  const recipesById = new Map<number, import('@/types').Recipe>();
  return {
    shoppingList: [] as ShoppingListItem[],
    pantryItems: [] as PantryItem[],
    recipes: [] as import('@/types').Recipe[],
    quickAddItem: '',
    draggedItem: null as ShoppingListItem | null,
    dropTargetInfo: null as { itemId?: number; category: string } | null,
    pendingAction: null,
    confirmationDialog: null,
    activeItems: [] as ShoppingListItem[],
    completedItems: [] as ShoppingListItem[],
    groupedList: {} as Record<string, ShoppingListItem[]>,
    recipesById,
    addItemInputRef: { current: null as HTMLInputElement | null },
    status: 'idle' as const,
    isAiModalOpen: false,
    isBulkAddModalOpen: false,
    editingItem: null as ShoppingListItem | null,
    editingCategory: null as { oldName: string; newName: string } | null,
    isCompletedVisible: true,
    isExportOpen: false,
    isShoppingMode: false,
    collapsedCategories: [] as string[],
    isGenerating: false,
    error: null as string | null,
    setQuickAddItem: vi.fn(),
    setAiModalOpen: vi.fn(),
    setBulkAddModalOpen: vi.fn(),
    setEditingItem: vi.fn(),
    setEditingCategory: vi.fn(),
    setIsCompletedVisible: vi.fn(),
    setExportOpen: vi.fn(),
    setShoppingMode: vi.fn(),
    setDropTargetInfo: vi.fn(),
    handleToggle: vi.fn(),
    handleQuickAdd: vi.fn(),
    handleAiAdd: vi.fn(),
    handleBulkAdd: vi.fn(),
    handleGenerateFromPlan: vi.fn(),
    handleClearList: vi.fn(),
    handleExport: vi.fn(),
    handleRenameCategory: vi.fn(),
    handleToggleCategoryCollapse: vi.fn(),
    collapseAll: vi.fn(),
    expandAll: vi.fn(),
    handleDragStart: vi.fn(),
    handleDragOver: vi.fn(),
    handleDrop: vi.fn(),
    onCategoryDrop: vi.fn(),
    onDragEnd: vi.fn(),
    handleMoveToPantry: vi.fn(),
    confirmPendingAction: vi.fn(),
    cancelPendingAction: vi.fn(),
    updateItem: vi.fn(),
    deleteItem: vi.fn(),
  };
}
